# CA 2026 primary top-2 winners per district, extracted from the official
# Statement of Vote PDF (elections.cdn.sos.ca.gov/sov/2026-primary/sov/complete-sov.pdf),
# pages 76-92 (printed pages 73-89), "United States Representative" section.
# Format: district -> [last_name_lower, ...] (top 2 vote-getters, CA top-two system)
TRUTH = {
    1: ["gallagher", "mcguire"],
    2: ["huffman", "littau"],
    3: ["bera", "tucker"],
    4: ["thompson", "jones"],
    5: ["mcclintock", "masuda"],
    6: ["kiley", "pan"],
    7: ["vang", "wooden"],
    8: ["garamendi", "recile"],
    9: ["harder", "mcbride"],
    10: ["desaulnier", "frese"],
    11: ["wiener", "chan"],
    12: ["simon", "joyce"],
    13: ["gray", "lincoln"],
    14: ["wahab", "huang"],
    15: ["mullin", "hoelter"],
    16: ["liccardo", "soulé", "soule"],
    17: ["khanna", "tandon"],
    18: ["lofgren", "lewis"],
    19: ["panetta", "verbica"],
    20: ["fong", "scotter"],  # Sandra Van Scotter
    21: ["costa", "kirkland"],
    22: ["valadao", "villegas"],
    23: ["obernolte", "hodge"],
    24: ["carbajal", "smith"],
    25: ["ruiz", "males"],
    26: ["irwin", "gallucci"],
    27: ["gibbs", "whitesides"],
    28: ["chu", "verlato"],
    29: ["rivas", "melendez"],
    30: ["friedman", "meyers"],
    31: ["cisneros", "ching"],
    32: ["sherman", "thompson"],
    33: ["aguilar", "vargas"],
    34: ["gomez", "lee"],
    35: ["torres", "cargile"],
    36: ["lieu", "brignano"],
    37: ["kamlager-dove", "kamlager", "fedalizo"],
    38: ["solis", "casas"],
    39: ["takano", "manos"],
    40: ["calvert", "kim"],
    41: ["sánchez", "sanchez", "clemmons"],
    42: ["garcia", "blom"],  # Noah Von Blom
    43: ["waters", "morales"],
    44: ["barragan", "angel"],
    45: ["tran", "vo"],
    46: ["correa", "pan"],
    47: ["min", "leroux", "le roux"],
    48: ["desmond", "wilpert"],  # Marni von Wilpert
    49: ["levin", "kurdian"],
    50: ["peters", "cohen"],
    51: ["jacobs", "cabrera"],
    52: ["vargas", "belle"],
}
