# Source: en.wikipedia.org/wiki/2026_United_States_House_of_Representatives_elections_in_Florida
NOMINEES = {
    1: [("Jimmy Patronis", "Republican"), ("Gay Valimont", "Democratic")],
    2: [("Austin Rogers", "Republican"), ("Amanda Green", "Democratic")],
    3: [("Kat Cammack", "Republican"), ("Seth Harp", "Democratic")],
    4: [("Aaron Bean", "Republican"), ("LaShonda Holloway", "Democratic")],
    5: [("John Rutherford", "Republican"), ("Rachel Grage", "Democratic")],
    6: [("Randy Fine", "Republican"), ("Eric Yonce", "Democratic")],
    7: [("Ryan Elijah", "Republican"), ("Bale Dalton", "Democratic")],
    8: [("Mike Haridopolos", "Republican"), ("Jennifer Jenkins", "Democratic")],
    9: [("Darren Soto", "Democratic"), ("Dan Green", "Republican")],
    10: [("Maxwell Frost", "Democratic")],
    11: [("Joe Strada", "Republican"), ("James Pericola", "Democratic")],
    12: [("Gus Bilirakis", "Republican"), ("Kimberly Overman", "Democratic")],
    13: [("Anna Paulina Luna", "Republican"), ("Leela Gray", "Democratic")],
    14: [("Kathy Castor", "Democratic"), ("Mike Beltran", "Republican")],
    15: [("Laurel Lee", "Republican"), ("Robert People", "Democratic")],
    16: [("Sydney Gruters", "Republican"), ("Kelly Kirschner", "Democratic")],
    17: [("Greg Steube", "Republican"), ("Matthew Montavon", "Democratic")],
    18: [("Scott Franklin", "Republican"), ("Curtis Gibson", "Democratic")],
    19: [("Jim Schwartzel", "Republican"), ("Victor Arias", "Democratic")],
    20: [("Debbie Wasserman Schultz", "Democratic"), ("Brent Andersen", "Republican")],
    21: [("Brian Mast", "Republican"), ("James Martin", "Democratic")],
    22: [("Pia Dandiya", "Democratic"), ("Casey Askar", "Republican")],
    23: [("Lois Frankel", "Democratic"), ("Deborah Adeimy", "Republican")],
    24: [("Oliver Gilbert", "Democratic"), ("Mayonna Te Brown", "Republican")],
    25: [("Jared Moskowitz", "Democratic"), ("Scott Singer", "Republican")],
    26: [("Mario Díaz-Balart", "Republican"), ("Nicole Locklin", "Democratic")],
    27: [("Maria Elvira Salazar", "Republican"), ("Eliott Rodriguez", "Democratic")],
    28: [("Carlos Giménez", "Republican"), ("Phil Ehr", "Democratic")],
}
