# Source: en.wikipedia.org/wiki/2026_United_States_House_of_Representatives_elections_in_New_York
NOMINEES = {
    1: [("Nick LaLota", "Republican"), ("Chris Gallant", "Democratic")],
    2: [("Andrew Garbarino", "Republican"), ("Patrick Halpin", "Democratic")],
    3: [("Tom Suozzi", "Democratic"), ("Mike LiPetri", "Republican")],
    4: [("Laura Gillen", "Democratic"), ("Jeanine Driscoll", "Republican")],
    5: [("Gregory Meeks", "Democratic"), ("George Marsh", "Republican")],
    6: [("Grace Meng", "Democratic"), ("Joseph Chou", "Republican")],
    7: [("Claire Valdez", "Democratic"), ("Melvin Rivera", "Republican")],
    8: [("Hakeem Jeffries", "Democratic"), ("Lewis Mizrahi", "Republican")],
    9: [("Yvette Clarke", "Democratic"), ("Joel Anabilah-Azumah", "Republican")],
    10: [("Brad Lander", "Democratic"), ("Jennifer Moore", "Republican")],
    11: [("Nicole Malliotakis", "Republican"), ("Michael DeCillis", "Democratic")],
    12: [("Micah Lasher", "Democratic"), ("Caroline Shinkle", "Republican")],
    13: [("Darializa Avila Chevalier", "Democratic"), ("Jomo M. Williams", "Republican")],
    14: [("Alexandria Ocasio-Cortez", "Democratic"), ("Diamant Hysenaj", "Republican")],
    15: [("Ritchie Torres", "Democratic"), ("Stylo Sapaskis", "Republican")],
    16: [("George Latimer", "Democratic"), ("Joseph Cinquemani", "Republican")],
    17: [("Mike Lawler", "Republican"), ("Cait Conley", "Democratic")],
    18: [("Pat Ryan", "Democratic"), ("Jacqueline Auringer", "Republican")],
    19: [("Josh Riley", "Democratic"), ("Peter Oberacker", "Republican")],
    20: [("Paul Tonko", "Democratic"), ("Ralph Ambrosio", "Republican")],
    21: [("Anthony Constantino", "Republican"), ("Blake Gendebien", "Democratic")],
    22: [("John Mannion", "Democratic"), ("Kailee Buller", "Republican")],
    23: [("Nick Langworthy", "Republican"), ("Aaron Gies", "Democratic")],
    24: [("Claudia Tenney", "Republican"), ("Alissa Ellman", "Democratic")],
    25: [("Joseph Morelle", "Democratic"), ("Virginia McIntyre", "Republican")],
    26: [("Tim Kennedy", "Democratic"), ("Dennis Hannon", "Republican")],
}
