# Source: en.wikipedia.org/wiki/2026_United_States_House_of_Representatives_elections_in_Texas
NOMINEES = {
    1: [("Nathaniel Moran", "Republican"), ("Yolanda Prince", "Democratic")],
    2: [("Steve Toth", "Republican"), ("Shaun Finnie", "Democratic")],
    3: [("Keith Self", "Republican"), ("Evan Hunt", "Democratic")],
    4: [("Pat Fallon", "Republican"), ("Jason Pearce", "Democratic")],
    5: [("Lance Gooden", "Republican"), ("Chelsey Hockett", "Democratic")],
    6: [("Jake Ellzey", "Republican"), ("Danny Minton", "Democratic")],
    7: [("Lizzie Fletcher", "Democratic"), ("Alexander Hale", "Republican")],
    8: [("Jessica Steinmann", "Republican"), ("Laura Jones", "Democratic")],
    9: [("Leticia Gutierrez", "Democratic"), ("Alex Mealer", "Republican")],
    10: [("Chris Gober", "Republican"), ("Caitlin Rourk", "Democratic")],
    11: [("August Pfluger", "Republican"), ("Claire Reynolds", "Democratic")],
    12: [("Craig Goldman", "Republican"), ("Angela Rodriguez Prilliman", "Democratic")],
    13: [("Ronny Jackson", "Republican"), ("Mark Nair", "Democratic")],
    14: [("Randy Weber", "Republican"), ("Thurman Bartie", "Democratic")],
    15: [("Monica De La Cruz", "Republican"), ("Bobby Pulido", "Democratic")],
    16: [("Veronica Escobar", "Democratic"), ("Adam Bauman", "Republican")],
    17: [("Pete Sessions", "Republican"), ("Casey Shepard", "Democratic")],
    18: [("Christian Menefee", "Democratic"), ("Ronald Whitfield", "Republican")],
    19: [("Tom Sell", "Republican"), ("Kyle Rable", "Democratic")],
    20: [("Joaquin Castro", "Democratic"), ("Edgardo Baez", "Republican")],
    21: [("Mark Teixeira", "Republican"), ("Kristin Hook", "Democratic")],
    22: [("Trever Nehls", "Republican"), ("Marquette Greene-Scott", "Democratic")],
    23: [("Brandon Herrera", "Republican"), ("Katy Padilla Stout", "Democratic")],
    24: [("Beth Van Duyne", "Republican"), ("Kevin Burge", "Democratic")],
    25: [("Roger Williams", "Republican"), ("Dione Sims", "Democratic")],
    26: [("Brandon Gill", "Republican"), ("Steven Shook", "Democratic")],
    27: [("Michael Cloud", "Republican"), ("Tanya Lloyd", "Democratic")],
    28: [("Henry Cuellar", "Democratic"), ("Tano Tijerina", "Republican")],
    29: [("Sylvia Garcia", "Democratic"), ("Martha Fierro", "Republican")],
    30: [("Frederick Haynes III", "Democratic"), ("Everett Jackson", "Republican")],
    31: [("John Carter", "Republican"), ("Justin Early", "Democratic")],
    32: [("Dan Barrios", "Democratic"), ("Jace Yarbrough", "Republican")],
    33: [("Colin Allred", "Democratic"), ("Patrick Gillespie", "Republican")],
    34: [("Vicente Gonzalez", "Democratic"), ("Eric Flores", "Republican")],
    35: [("Johnny Garcia", "Democratic"), ("Carlos De La Cruz", "Republican")],
    36: [("Brian Babin", "Republican"), ("Rhonda Hart", "Democratic")],
    37: [("Greg Casar", "Democratic"), ("Lauren Peña", "Republican")],
    38: [("Jon Bonck", "Republican"), ("Melissa McDonough", "Democratic")],
}
